sonar.organization=genesys-fatec
sonar.projectKey=genesys-fatec_API-4DSM-PROCESSADOR-DADOS
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml